const countryObjectType = {
  "USA": "US",
  "Canada": "CA",
  "Russia": "RU",
  "France": "FR",
  "Germany": "DE",
  "UK": "GB",
  "Australia": "AU",
  "NATO": "NATO",
  "China": "CN",
  "Japan": "JP",
  "Spain": "ES",
  "Indonesia": "ID",
  "I-ESA": "I-ESA",
  "Italy": "IT",
  "India": "IN",
  "ARABSAT": "ARABSAT",
  "Brazil": "BR",
  "Mexico": "MX",
  "Sweden": "SE",
  "EUMETSAT": "EUMETSAT",
  "Luxembourg": "LU",
  "CSSR": "CSSR",
  "Argentina": "AR",
  "INTELSAT": "INTELSAT",
  "HKUK": "HKUK",
  "CSFR": "CSFR",
  "RU": "RU",
  "South Korea": "KR",
  "Portugal": "PT",
  "Thailand": "TH",
  "Turkey": "TR",
  "Ukraine": "UA",
  "Czechoslovakia": "CZ",
  "Norway": "NO",
  "China(Hong Kong)": "HK",
  "Egypt": "EG",
  "Chile": "CL",
  "Israel": "IL",
  "Singapore": "SG",
  "Denmark": "DK",
  "South Africa": "ZA",
  "Cayman Is.": "KY",
  "Malaysia": "MY",
  "Saudi Arabia": "SA",
  "UAE": "AE",
  "Pakistan": "PK",
  "Morocco": "MA",
  "Netherlands": "NL",
  "Algeria": "DZ",
  "Greece": "GR",
  "Nigeria": "NG",
  "Taiwan": "TW",
  "Iran": "IR",
  "Kazakhstan": "KZ",
  "Colombia": "CO",
  "RASCOM": "RASCOM",
  "Vietnam": "VN",
  "Venezuela": "VE",
  "Switzerland": "CH",
  "Belarus": "BY",
  "North Korea": "KP",
  "Azerbaijan": "AZ",
  "Austria": "AT",
  "Ecuador": "EC",
  "Estonia": "EE",
  "Poland": "PL",
  "Peru": "PE",
  "Bolivia": "BO",
  "Belgium": "BE",
  "Uruguay": "UY",
  "EU": "EU",
  "Papua New Guinea": "PG",
  "Monaco": "MC",
  "Laos": "LA",
  "Phillipines": "PH",
  "Qatar": "QA",
  "Finland": "FI",
  "Jordan": "JO",
  "Lithuania": "LT",
  "New Zealand": "NZ",
  "Sudan": "SD",
  "Ethiopia": "ET",
  "Slovenia": "SI",
  "US": "US",
  "Tunisia": "TN",
  "Slovakia": "SK",
  "Hungary": "HU",
  "Kuwait": "KW",
  "BGN": "BGN",
  "Nepal": "NP",
  "0": "0",
  "Angola": "AO",
  "Bhutan": "BT",
  "Kenya": "KE",
  "Romania": "RO",
  "PRC": "PRC",
  "SES": "SES"
};

export default countryObjectType;
